package dto;

import engine.*;

import java.util.ArrayList;
import java.util.List;

public record UserOrderBookPositionDTO(
        List<HoldingDTO> holdings,
        double commissionPaid,
        boolean eventClosed,
        Double profitLoss   // null while the event is open
) {
    public UserOrderBookPositionDTO(Event event, User user) {
        this(
                buildHoldings(event, user.getName()),
                sumCommission(event, user.getName()),
                event.getEventTradingStatus().getStatus() == EventTradingStatus.Status.CLOSED,
                computeProfitLoss(event, user)
        );
    }

    private static Holding[] holdingsOf(Event event, String userName) {
        Holding[] holdings = event.getUserHoldings(userName);
        return holdings != null ? holdings : new Holding[] {
                new Holding(event.getOptions().getFirst().getOptionName()),
                new Holding(event.getOptions().get(1).getOptionName())
        };
    }

    private static List<HoldingDTO> buildHoldings(Event event, String userName) {
        Holding[] h = holdingsOf(event, userName);
        List<Option> options = event.getOptions();
        List<HoldingDTO> list = new ArrayList<>();
        for (int i = 0; i < options.size(); i++) {
            list.add(new HoldingDTO(
                    options.get(i).getOptionName(),
                    h[i].getShares(),
                    h[i].getTotalPaid(),
                    h[i].getCommissionPaid()));
        }
        return list;
    }

    private static double sumCommission(Event event, String userName) {
        return event.getEventTradingStatus().getTradingHistory().stream()
                .filter(t -> t.userName().equals(userName))
                .mapToDouble(Trade::commissionPaid)
                .sum();
    }

    private static Double computeProfitLoss(Event event, User user) {

        if (event.getEventTradingStatus().getStatus() != EventTradingStatus.Status.CLOSED) {
            return null;
        }

        if (!(event.getMethod() instanceof OrderBook ob)) {
            return null;
        }

        Holding[] holdings = holdingsOf(event, user.getName());
        List<Option> options = event.getOptions();

        Integer winnerIdx = getWinnerIdx(options);
        if (winnerIdx == null)
            return null;

        /*
         * totalPaid is already NET cash spent:
         *
         * BUY  -> increases totalPaid
         * SELL -> decreases totalPaid
         *
         * So it already accounts for money received from selling shares.
         */
        double totalInvested =
                holdings[0].getTotalPaid()
                        + holdings[1].getTotalPaid();

        // Winning shares payout
        double gross = holdings[winnerIdx].getShares() * ob.getValue();

        boolean onClose = "on-close".equals(event.getCommission().getCommissionType());

        double percentage = event.getCommission().getValue() / 100.0;

        // Commission this user pays when redeeming winning shares
        double closingCommission = onClose ? gross * percentage : 0.0;

        double netPayout = gross - closingCommission;

        double profitLoss = netPayout - totalInvested;

        /*
         * The MM receives ALL commissions generated by this event,
         * not just the commission from their own position.
         */
        boolean isMaker = event.getUsersHoldings().containsKey(user.getName())
                        && user.isMarketMaker(event.getId()); // use your actual MM check

        if (isMaker) {
            profitLoss += event.getEventTradingStatus().getTotalCommissionPaid();
        }

        return profitLoss;
    }

    private static Integer getWinnerIdx(List<Option> options) {
        // Find winning option
        int winnerIdx = -1;

        for (int i = 0; i < options.size(); i++) {
            if (options.get(i).getIsWinner()) {
                winnerIdx = i;
                break;
            }
        }

        if (winnerIdx == -1) {
            return null;
        }
        return winnerIdx;
    }
}